[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "radcomp"
version = "1.0.0b"

dependencies = [
    "numpy",
    "scipy",
    "CoolProp >= 6.4.3",
]

[tool.setuptools]
packages = ['radcomp']
